#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERP.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ERP_INFO")]
	public partial class MiniErpDB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 확장성 메서드 정의
    partial void OnCreated();
    #endregion
		
		public MiniErpDB() : 
				base(global::MiniERP.Properties.Settings.Default.ERP_INFOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MiniErpDB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiniErpDB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiniErpDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiniErpDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MODIFY_TRADE")]
		public int MODIFY_TRADE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string trade_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string clerk_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string warehouse_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string trade_status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trade_code, clerk_code, warehouse_code, trade_status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_MANUFACTURE_PLAN")]
		public ISingleResult<GET_MANUFACTURE_PLANResult> GET_MANUFACTURE_PLAN([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string order_code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), order_code);
			return ((ISingleResult<GET_MANUFACTURE_PLANResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_RESOURCES_PLAN")]
		public ISingleResult<GET_RESOURCES_PLANResult> GET_RESOURCES_PLAN([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string ordere_code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ordere_code);
			return ((ISingleResult<GET_RESOURCES_PLANResult>)(result.ReturnValue));
		}
	}
	
	public partial class GET_MANUFACTURE_PLANResult
	{
		
		private string _Item_code;
		
		private string _Item_name;
		
		private System.Nullable<int> _M;
		
		private string _Item_standard;
		
		public GET_MANUFACTURE_PLANResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_code", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Item_code
		{
			get
			{
				return this._Item_code;
			}
			set
			{
				if ((this._Item_code != value))
				{
					this._Item_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item_name
		{
			get
			{
				return this._Item_name;
			}
			set
			{
				if ((this._Item_name != value))
				{
					this._Item_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M", DbType="Int")]
		public System.Nullable<int> M
		{
			get
			{
				return this._M;
			}
			set
			{
				if ((this._M != value))
				{
					this._M = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_standard", DbType="NVarChar(20)")]
		public string Item_standard
		{
			get
			{
				return this._Item_standard;
			}
			set
			{
				if ((this._Item_standard != value))
				{
					this._Item_standard = value;
				}
			}
		}
	}
	
	public partial class GET_RESOURCES_PLANResult
	{
		
		private string _part_code;
		
		private string _item_name;
		
		private System.Nullable<int> _item_count;
		
		private string _item_standard;
		
		public GET_RESOURCES_PLANResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_code", DbType="NVarChar(20)")]
		public string part_code
		{
			get
			{
				return this._part_code;
			}
			set
			{
				if ((this._part_code != value))
				{
					this._part_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="NVarChar(50)")]
		public string item_name
		{
			get
			{
				return this._item_name;
			}
			set
			{
				if ((this._item_name != value))
				{
					this._item_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_count", DbType="Int")]
		public System.Nullable<int> item_count
		{
			get
			{
				return this._item_count;
			}
			set
			{
				if ((this._item_count != value))
				{
					this._item_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_standard", DbType="NVarChar(20)")]
		public string item_standard
		{
			get
			{
				return this._item_standard;
			}
			set
			{
				if ((this._item_standard != value))
				{
					this._item_standard = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
