<?xml version="1.0" encoding="utf-8"?><Database Name="ERP_INFO" Class="MiniErpDB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tokoyy.database.windows.net;Initial Catalog=ERP_INFO;Persist Security Info=True;User ID=GD" SettingsObjectName="MiniERP.Properties.Settings" SettingsPropertyName="ERP_INFOConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.MODIFY_TRADE" Method="MODIFY_TRADE">
    <Parameter Name="trade_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="clerk_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="warehouse_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="trade_status" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GET_MANUFACTURE_DOC" Method="GET_MANUFACTURE_DOC">
    <Parameter Name="Manufactdate" Parameter="manufactdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="warehouse_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GET_MANUFACTURE_DOCResult">
      <Column Name="Item_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Distribution_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GET_RESOURCES_PLAN" Method="GET_RESOURCES_PLAN">
    <Parameter Name="ordere_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GET_RESOURCES_PLANResult">
      <Column Name="part_code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="item_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="item_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GET_PURCHASE_PLAN" Method="GET_PURCHASE_PLAN">
    <Parameter Name="ordere_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GET_PURCHASE_PLANResult">
      <Column Name="part_code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="item_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="item_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GET_ORDER" Method="GET_ORDER">
    <Parameter Name="Order_code" Parameter="order_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GET_ORDERResult">
      <Column Name="item_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_wrote_fee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Item_unit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SET_STOCK_ITEM" Method="SET_STOCK_ITEM">
    <Parameter Name="item_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="warehouse_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="stock_count" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GET_STOCK" Method="GET_STOCK">
    <Parameter Name="warehouse_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="item_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GET_STOCKResult">
      <Column Name="Item_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warehouse_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Warehouse_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Stock_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GET_DISTRIBUTION" Method="GET_DISTRIBUTION">
    <Parameter Name="low_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="max_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="before_warehouse" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="after_warehouse" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="item_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="status" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="PageNumber" Parameter="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="RowsPerPage" Parameter="rowsPerPage" Type="System.Int32" DbType="Int" />
    <ElementType Name="GET_DISTRIBUTIONResult">
      <Column Name="Distribution_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Before_warehouse" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="After_warehouse" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Distribution_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Distribution_status" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Export" Method="Get_Export">
    <Parameter Name="move_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="before_warehouse" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="Get_ExportResult">
      <Column Name="afterName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Distribution_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_Import" Method="Get_Import">
    <Parameter Name="move_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="after_warehouse" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="Get_ImportResult">
      <Column Name="beforeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Distribution_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GET_MANUFACTURE_PLAN" Method="GET_MANUFACTURE_PLAN">
    <Parameter Name="order_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="GET_MANUFACTURE_PLANResult">
      <Column Name="Item_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="M" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Item_wrote_fee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SET_DISTRIBUTION" Method="SET_DISTRIBUTION">
    <Parameter Name="order_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="before_warehouse" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="after_warehouse" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="item_code" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="distribution_count" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="move_date" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Specific_Business" Method="Get_Specific_Business">
    <Parameter Name="Business_code" Parameter="business_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="Get_Specific_BusinessResult">
      <Column Name="Business_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Business_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Business_tel" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Business_addr" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Business_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Business_presenter" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PROC_STATEMENT" Method="PROC_STATEMENT">
    <Parameter Name="order_code" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="PROC_STATEMENTResult">
      <Column Name="Item_code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Item_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_standard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Item_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_wrote_fee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>