<?xml version="1.0" encoding="utf-8"?><Database Name="ERP_INFO" Class="MiniErpDB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tokoyy.database.windows.net;Initial Catalog=ERP_INFO;Persist Security Info=True;User ID=GD" SettingsObjectName="MiniERP.Properties.Settings" SettingsPropertyName="ERP_INFOConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.MODIFY_TRADE" Method="MODIFY_TRADE">
    <Parameter Name="trade_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="clerk_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="warehouse_code" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="trade_status" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
</Database>